apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: init
  name: init
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: init
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: init
    spec:
      containers:
      - env:
        - name: MONGODB_CONNECTION
          value: mongodb://mongo:27017/contentdb
        image: docker.pkg.github.com/joshwencl/chaos-setup/fabrikam-init:latest
        imagePullPolicy: ""
        name: init
        resources: {}
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
      serviceAccountName: ""
      volumes: null
status: {}
