version: "3.4"
services:
  mongo:
    image: mongo
    restart: always

  api:
    build: ./content-api
    image: ghcr.io/joshwencl/fabrikam-api:latest
    depends_on:
      - mongo
    environment:
      MONGODB_CONNECTION: mongodb://mongo:27017/contentdb      
      
  web:
     build: ./content-web
     image: ghcr.io/joshwencl/fabrikam-web:latest