version: "3.4"
services:
  mongo:
    image: mongo
    restart: always

  init:
    build: ./content-init
    image: https://ghcr.io/joshwencl/chaos-setup/fabrikam-init:latest
    depends_on:
      - mongo
    environment:
      MONGODB_CONNECTION: mongodb://mongo:27017/contentdb

  api:
    image: https://ghcr.io/joshwencl/chaos-setup/fabrikam-api:latest
    depends_on:
      - mongo
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      MONGODB_CONNECTION: mongodb://mongo:27017/contentdb      

  web:
    image: https://ghcr.io/joshwencl/chaos-setup/fabrikam-web:latest
    depends_on:
        - api
    environment:
       CONTENT_API_URL: http://api:3001
    ports:
      - "3000:80"       